export const CheckoutActionTypes = {
  CHECKOUT_START: "CHECKOUT_START",
  CHECKOUT_PROCESSING: "CHECKOUT_PROCESSING",
  CHECKOUT_SUCCEDED: "CHECKOUT_SUCCEDED",
  CHECKOUT_RESET: "CHECKOUT_RESET",
  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS"
};
